# to accelerate training
use_amp: true
cudnn_benchmark: false
cudnn_deterministic: false


# network architecture

# # frontend related
# frontend: default
# frontend_conf:
#    n_fft: 512
#    win_length: 400
#    hop_length: 160

#frontend related
#freeze_param: ["frontend.upstream"]
frontend: fused
frontend_conf:
  frontends:
    - frontend_type: s3prl
      frontend_conf:
        upstream: tera
      download_dir: ./hub
      multilayer_feature: True

    - frontend_type: default
      n_fft: 512
      win_length: 400
      hop_length: 160

      #    - frontend_type: s3prl
      # frontend_conf:
      #   upstream: wav2vec
      # download_dir: ./hub
      # multilayer_feature: True

  align_method: linear_projection
  proj_dim: 100

preencoder: linear
preencoder_conf:
    input_size: 200  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 100


# encoder related
encoder: conformer
encoder_conf:
    input_layer: conv2d
    num_blocks: 6
    linear_units: 1024
    dropout_rate: 0.3
    output_size: 256
    attention_heads: 4
    attention_dropout_rate: 0.0
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 15


# decoder related
decoder: transformer
decoder_conf:
    input_layer: embed
    num_blocks: 4
    linear_units: 1024
    dropout_rate: 0.3

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

# optimization related
optim: adam
accum_grad: 1
grad_clip: 3
max_epoch: 100
optim_conf:
    lr: 4.0
scheduler: noamlr
scheduler_conf:
    model_size: 256
    warmup_steps: 25000

# minibatch related
batch_type: numel
batch_bins: 10000000

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
